### ISSUE TITLE
Why Quack?

### ISSUE THREAD

**Issue by bvssvni** [PistonDevelopers/quack#10]
Assume we have the following trait with a property pattern:

``` Rust
pub trait Foo {
    set_x(&mut self, val: f64);
    get_x(&mut self) -> f64;
    set_y(&mut self, val: f64);
    get_y(&mut self) -> f64;
    set_z(&mut self, val: f64);
    get_z(&mut self) -> f64;
}
```

What if we had another trait `Bar` that only needed `x` and `y`? Should we make `Foo` inherit `Bar` to save code? Or, perhaps we should just use `Foo` even if we don't need `z`? The larger libraries you write, such problems tends to get hairier and uglier to deal with.

This problem can be solved with something called "duck typing". Instead of creating large traits with many methods, you try to make them as small as possible. 

``` Rust
pub trait X {
     set_x(&mut self, val: f64);
     get_x(&self) -> f64;
}
```

Now, you can make `Foo` inherit `X`:

``` Rust
pub trait Foo: X + Y + Z {}
```

There is a problem with this: What if we can set an x value, but not get one? We could split the traits into `GetX`, `SetX` etc.

Yet, there is another problem: Some people use a `get_mut/get` pattern. `get_mut` only works when there is an interior pointer to the type. For example, it won't work if you need to convert an `i32` to `i64`.

Then, there is another problem: Some people like the builder pattern:

``` Rust
let x = Foo::new(...).bar(1.0).baz(2.0);
```

Then, there is yet another problem: In generic code, people might want to put a shared object inside a struct with `&RefCell<T>` or `Rc<RefCell<T>>`, but they also might want it work with an owned object:

``` Rust
struct Foo<T> {
    a: T,
}

struct Foo<'a, T> {
    a: &'a RefCell<T>
}

struct Foo<T> {
    a: Rc<RefCell<T>>
}
```

This can lead to inconsistent API design where one library might not work with another because it uses different smart pointers. Sometimes we want more control in performance sensitive code to pick a smart pointer implementation, but when this is not case, we just want to have a nice get/set pattern.

Let's write up all the problems so far:
- Shared properties between traits
- Incompatible get/set patterns
- Builder pattern
- Smart pointers in generic code

When using Piston-Quack, you define a get/set pattern by using `GetFrom` and `SetAt`.

``` Rust
impl<'a> GetFrom for (Position, Label<'a>) {
    #[inline(always)]
    fn get_from(label: &Label<'a>) -> Position {
        Position(label.pos)
    }
}

impl<'a> SetAt for (Position, Label<'a>) {
    #[inline(always)]
    fn set_at(Position(pos): Position, label: &mut Label<'a>) {
        label.pos = pos;
    }
}
```

This can be shortend down by using the `quack!` macro:

``` Rust
quack! {
    label: Label['a]
    get:
        fn () -> Position [] { Position(label.pos) }
    set:
        fn (val: Position) [] { label.pos = val.0 }
    action:
}
```

When using the library, we can import the `Get` and `Set` traits:

``` Rust
use quack::Set;
use Position;

foo.set(Position([1.0, 2.0]));
```

This also has the advantage that the imported type `Position` is the same as how you call the method.

More, it simplifies process when designing a new API:
1. Add structs and enums for the data types
2. Add `GetFrom/SetAt/ActOn` impls
3. Done!

Now, if we want to extend the API with new methods, we could make the _traits inherit the properties_!

Here is an example:

``` Rust
pub trait RelativeTransform: Clone 
    where
        (Transform, Self): Pair<Data = Transform, Object = Self> + GetFrom + SetAt
{
    /// Appends transform to the current one.
    #[inline(always)]
    fn append_transform(&self, transform: Matrix2d) -> Self {
        let Transform(mat) = self.get();
        self.clone().set(Transform(multiply(mat, transform)))
    }

    // a bunch of other methods
    ...
}
```

The `Pair` constraint is necessary at the moment to make Rust understand the tuple. This might disappear when Rust gets full equality constraints.

Now we can auto implement the trait for all types that has these properties:

``` Rust
impl<T: Clone> RelativeTransform for T
    where
        (Transform, Self): Pair<Data = Transform, Object = Self> + GetFrom + SetAt
{}
```

**Comment by bvssvni** [comment]
### Imported types have the same name as way methods are called

When importing a trait, you add methods to an object in the code. There is no easy way to keep track of which methods belongs to which traits:

```Rust
use Foo;

x.foo(); // does this belongs to `Foo`?
```

Piston-Quack bridges this gap in the conceptual model:

```Rust
use Text;

x.set(Text("hello"));
```

**Comment by bvssvni** [comment]
### Extra type safety

Assume that you return a number in units. Without wrapping this in a type, there is nothing that prevents you from accidentally use it with the wrong units:

```Rust
let radius = foo.get_radius();
bar.set_radius(radius); // `bar` might use another unit than `foo`
```

Pisotn-Quack returns a property, such that the conversion of units is explicit:

```Rust
let RadiusInMeters(radius) = foo.get();
bar.set(RadiusInKm(radius / 1000.0);
```

This is true not only for units, but for any different *usage*. For example, a matrix has different usage as a `Transform` and `ViewTransform`, and setting the wrong property might cause bugs that are not easily tracked down. This gives some extra type safety when redesigning or refactoring.

**Comment by aepsil0n** [comment]
I am very sceptical about this. I don't know if this topic is open for debate. However, I thought that this is the right place to share my concerns and that it's better to do so than to silently stay away. I do care a lot about Rust's gamedev infrastructure and Piston is a huge part of that.

Quite frankly: this is exactly the kind of anti-pattern, that's currently driving me away from using Piston (along with current objects). This criticism cannot be constructive towards quack, as I am essentially saying that properly designed software does not need it at all. So please forgive me, if this sounds a bit negative. Nonetheless, I write this with the intention of being constructive with respect to Piston at large and hoping that you reconsider the usage of this pattern throughout the framework.

The point is, that using accessors is considered an indicator of [bad](http://typicalprogrammer.com/doing-it-wrong-getters-and-setters/) [design](http://www.javaworld.com/article/2073723/core-java/why-getter-and-setter-methods-are-evil.html) (I really recommend reading those articles, in case you have never come across this sentiment). Code using the fields of a type (even when it's using highly abstracted accessors) should be implemented in a method instead. And even if you do that using those abstract accessors, exposing the properties in an API supports code that does not. And such code is not particularly reusable any way and thus could as well act on public attributes (which should be an intermediate state, before it is abstracted out).

Now I see that there is sometimes a need to work without abstractions to quickly implement something. This is not inherently wrong, but one should be aware of the fact, that code like that is not highly reusable and should not be depended upon too much or otherwise will become very difficult to maintain. However, abstracting the myriad of ways one could possibly implement accessors in Rust looks like you're going through great lengths to do the wrong thing (accessors) in the right way.

**Comment by bvssvni** [comment]
@aepsil0n I'm sorry to tell you this, but you are completely wrong on both accounts. Current objects are not part of the Piston core and not used in any of the other libraries. It is used to help prototyping games and write Processing like libraries. You are also wrong about this library which is about *duck typing* and not about accessors. Quack lifts this functionality over smart pointers to make generic code work with shared objects, something that is required to use the Window back-end in the game loop and in the application code. If you don't do this, then you lock the API down to a smart pointer that can't be changed later when hundreds of projects depend on it. It also gives builder methods and a reasonable good API design with very little effort, something that matters when you have a lot of libraries. You should also know that the macros inline the method to create no overhead.

Quack has saved us tons of hours already, and Current solves one of the biggest pain points for writing games in Rust. Neither are "pretty" solutions, I completely agree with you on that, but there *is no other way* until we know another way that takes care of the long list of concerns that matters. The core of Piston is to make it work with as little overhead as possible, and solve the problems that matters for a game engine core, which are problems *no other people are working on*. The Piston core solves these problems NOW and that is what matters for building other projects on top of it.
